Issue #190: Adding live audio processing
emilyperica/ScoreGen pull request #192
Opened 2024-12-23 23:49 UTC by emilyperica

﻿## GitHub Issue

Issue #190 

## Description

## How I tested

Used various input and output devices for recording and playback.

2024-12-23 23:51 UTC, emilyperica commented
@ianzachary Can you make sure the macOS specific sections work (i.e., sections of the code starting with #ifndef WIN32)?

2025-01-01 21:52 UTC, ianzachary requested changes
MacOS specific sections are good, but the I/O device param and info vars in recordAudio() need to be initialized before any of the goto jumps else segmentation errors.

2025-01-07 21:42 UTC, emilyperica commented
> MacOS specific sections are good, but the I/O device param and info vars in recordAudio() need to be initialized before any of the goto jumps else segmentation errors.

weird, do you know which vars specifically?

2025-01-11 00:54 UTC, ianzachary approved these changes

2025-01-11 19:16 UTC, merged