Updated development plan doc
emilyperica/ScoreGen pull request #22
Opened 2024-09-19 21:18 UTC by JaakLipp

﻿## GitHub Issue

[Issue #\12](https://github.com/emilyperica/ScoreGen/issues/12)

## Description

Included entire team charter section, along with info for IP, confidential info, and copyright license

2024-09-20 04:17 UTC, stoiyeet approved these changes

2024-09-20 13:12 UTC, emilyperica requested changes

2024-09-20 13:12 UTC, emilyperica commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +Our team will be adopting the \href{https://github.com/emilyperica/ScoreGen/blob/main/LICENSE}{MIT License}.
Can you add a few sentences explaining why you chose this license? Also go ahead and edit the LICENSE file to reflect this

2024-09-20 13:12 UTC, emilyperica commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +19/09/2024 & Jackson Lippert & Added confidential information, IP to protect, copyright license, and team charter sections\\
This only needs to be updated with any changes made after the initial draft (if anything this could have all our names with the description as Rev 0)

2024-09-23 00:31 UTC, emilyperica submitted a review, later dismissed
LGTM

2024-09-23 16:36 UTC, closed without merging