Issue 14: Expected tech
emilyperica/ScoreGen pull request #26
Opened 2024-09-20 21:00 UTC by ianzachary

﻿## GitHub Issue

Issue #14

## Description

Added section 10 expected technology to the DevelopmentPlan.tex.

## How I tested

Locally compiled changes successfully and viewed in PDF.

2024-09-21 17:29 UTC, emilyperica requested changes

2024-09-21 17:29 UTC, emilyperica commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +  Code Formatting & Linter(s) &  Specific tools are ndetermined at this stage as it is language dependant.
ndetermined -> undetermined

2024-09-21 17:29 UTC, emilyperica commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +  Testing & MATLAB unittest/automation, CMake, Unity, etc.  & Undetermined, likely a unit testing framework
Why unity? And when you say undetermined, does this mean the description itself is undetermined?

2024-09-21 17:29 UTC, emilyperica commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +depending on the implementation details, different metrics in addition to the basic ones such as statement coverage. For example, the designed algorithm
The sentence starting with 'One of the major...' is hard to understand, maybe split it into two sentences?

2024-09-22 15:42 UTC, ianzachary commented on docs/DevelopmentPlan/DevelopmentPlan.tex
> +  Testing & MATLAB unittest/automation, CMake, Unity, etc.  & Undetermined, likely a unit testing framework
Sorry, should have been more specific. I meant Unity Test, a C testing tool. It's mainly used for embedded systems but I wanted to include it as an example to be a bit broad in the possible choices.

2024-09-22 18:06 UTC, emilyperica submitted a review, later dismissed
LGTM

2024-09-24 13:59 UTC, emilyperica approved these changes

2024-09-24 14:00 UTC, merged