Issue #39: Requirements
emilyperica/ScoreGen pull request #64
Opened 2024-10-04 18:48 UTC by JaakLipp

﻿## GitHub Issue

Issue #39

## Description

Requirements sections for issue 39

## How I tested

COmpiled pdf locally

2024-10-09 15:25 UTC, emilyperica requested changes

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The interface between the user and the sheet music generator app shall within a reasonable time when processing input or selecting menu options.\\
think you missed 'respond' after 'generator app shall'

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The product shall respond in a reasonable time when users interact with its interface.
fit criterion should have testable values, 'reasonable' is subjective

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app’s graphical interface must comply with WCAG 2.1 (Web Content Accessibility Guidelines) for flashing content, limiting visual effects to fewer than 3 flashes per second
bibtex citation for WCAG

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} A critical requirement of this app is the precision at which it identifies notes. As a result, this app shall correctly detect musical pitch from instruments' input to ensure th
first sentence is unnecessary, if this requirement wasn't critical then you wouldn't be writing it down

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app must maintain this pitch accuracy over all test cases involving diverse instruments and note ranges, with no more than 1\% error.
should also discuss sound distortion, like if the user is too far from the mic or they're in a noisy room

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app must maintain timing accuracy within the specified tolerance across all test cases.
specify the tolerance in fit criterion

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} During stress testing under heavy load (e.g., multiple instruments or large file sizes), the app must maintain operational status and notify the user of delays or lowered perf
metric is confusing, 0/100 implies perfect success rate but it's hard to tell if that's what you meant - maybe just change this to match the percentage metrics you use in your other requirements

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app shall store up to 500 sheet music files per user, each up to 100MB in size, while maintaining access to all files without significant delays.\\
this requirement can be removed, the app leaves storage up to the user (i.e. we can't verify this because it will change per device running the app)

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app shall support at least 100 simultaneous user sessions (local or cloud-based) without degradation in performance or delays in processing.\\
100 users is overkill considering this is intended for personal use, not commercial, and the software (and thus processing) will be local to their device. Maybe reduce this to 10 or so?

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app shall scale to store up to 1 million sheet music files, each up to 100MB in size, by implementing efficient data storage and retrieval mechanisms.\\
don't need storage requirements

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app shall be capable of scaling to support an increase in the user base to 1000 users without requiring major architectural changes.\\
clarify that this scale up would be in moving from personal to business use

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app shall operate effectively across various computing environments, including different operating systems. The app shall also function reliably on devices with varying hard
initial design will only operate on windows

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app must be tested on screens ranging from 13 inches to 27 inches, with functionality and UI usability maintained across all typical screen sizes and resolutions.
what does screen size have to do with OS or hardware specs?

2024-10-09 15:25 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Standards/Protocols:} USB Audio Class.
why do you have all these extra subsections? everything in data content, physical content, and standards is just repeated from requirement and fit criterion.

2024-10-09 19:10 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The product shall respond in a reasonable time when users interact with its interface.
![image](https://github.com/user-attachments/assets/8a5a43de-1b84-4e9a-aa46-1b24639a08fc)
Unsure what to do

2024-10-09 19:46 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The product shall respond in a reasonable time when users interact with its interface.
lol me and Ian said the same thing - the *fit criterion* needs to have a quantifiable value. 'reasonable' is fine to use in the requirement but it needs to be more specific for the fit criterion.

2024-10-09 19:48 UTC, emilyperica commented
FYI, I'll re-review this once you've either made all the suggested changes or responded to my comments

2024-10-09 19:50 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app must maintain this pitch accuracy over all test cases involving diverse instruments and note ranges, with no more than 1\% error.
Noise is relevant here as well so just add a reference to OE-EP1

2024-10-10 21:57 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\textbf{Standards/Protocols:} USB Audio Class.
Makes sense will remove, idk it was just a lot of info so I felt like listing it out

2024-10-11 17:11 UTC, emilyperica approved these changes

2024-10-11 17:12 UTC, ianzachary approved these changes

2024-10-11 17:13 UTC, merged