Issue #38: added UI/UX requirements
emilyperica/ScoreGen pull request #68
Opened 2024-10-07 13:35 UTC by ianzachary

﻿## GitHub Issue

Issue #38

## Description

added section 10, 11 to SRS doc

## How I tested

Compiled locally, used chatgpt for spelling, grammar change suggestions.

2024-10-07 20:09 UTC, emilyperica requested changes

2024-10-07 20:09 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The app interface adheres human-centered design principles to be simple and intuitive to use.\\
requirements should always have 'must' - 'adheres' becomes 'must adhere'

2024-10-07 20:09 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The application must provide support for English (US).\\
can we do canadian english :(

2024-10-07 20:09 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} All text visible to the user shall be easily readable..\\
trailing '.' here can be removed

2024-10-07 20:09 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app will meet contrast ratios of at least 4.5:1 for normal text and 3:1 for large text.
why? include a citation here

2024-10-08 15:08 UTC, ianzachary commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The app will meet contrast ratios of at least 4.5:1 for normal text and 3:1 for large text.
will actually remove this req. entirely, just realized it's encapsulated by UH-A1

2024-10-08 19:06 UTC, JaakLipp requested changes

2024-10-08 19:06 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
>  \subsection*{LF-A3 Resolution}
For these subsections, could you use \subsubsection{} just to be consistent with mine and appear to fall under a certain requirement number

2024-10-08 19:06 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
>  \textbf{Requirement:} The app must comply with the standardized Web Content Accessibility Guidelines (WCAG).\\
could you add an href just to the guidelines we'll follow

2024-10-08 19:06 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\textbf{Requirement:} The application must appear authoritative and trustworthy.\\
could you add some justification for why this is a requirement

2024-10-11 17:01 UTC, JaakLipp approved these changes
LGTM as long as we add sources

2024-10-11 17:24 UTC, emilyperica approved these changes

2024-10-11 17:25 UTC, merged