Issue #40: Addition of security and maintainability NFRs
emilyperica/ScoreGen pull request #71
Opened 2024-10-07 21:38 UTC by emilyperica

﻿## GitHub Issue

Issue #40

## Description

title.
## How I tested
Compiled PDF locally

2024-10-09 03:29 UTC, stoiyeet submitted a review, later dismissed

2024-10-09 19:21 UTC, JaakLipp requested changes

2024-10-09 19:21 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\subsection*{MS-M2 System Crash}
A lot of the time people don't like when apps open by themselves, wondering if this should be a requirement or not

2024-10-09 19:21 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\textbf{Fit Criterion:} The development team shall be notified via email within 1 hour of a user submitting a report via the GUI.
maybe just take out 'via email', keeps the implementation details out in case we just have an internal list of bug reports as some other format

2024-10-09 19:41 UTC, emilyperica commented on docs/SRS-Volere/SRS.tex
> +\subsection*{MS-M2 System Crash}
this requirement specifies how the system will respond when the *user* opens the application

2024-10-10 22:01 UTC, JaakLipp commented on docs/SRS-Volere/SRS.tex
> +\subsection*{MS-M2 System Crash}
sorry this was for the after system crash^^

2024-10-11 18:50 UTC, merged